// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdZPn5AwfYKVdF7mX_cCby41gXqKFvOMc',
    appId: '1:122960398385:web:0519345325cb7c3b226d10',
    messagingSenderId: '122960398385',
    projectId: 'nutriplan-e06d0',
    authDomain: 'nutriplan-e06d0.firebaseapp.com',
    storageBucket: 'nutriplan-e06d0.firebasestorage.app',
    measurementId: 'G-1Y9X647CX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiALplU9cgwpDYjnPZWsNB_RsIWR9DPTU',
    appId: '1:122960398385:android:4b17a16f2a728002226d10',
    messagingSenderId: '122960398385',
    projectId: 'nutriplan-e06d0',
    storageBucket: 'nutriplan-e06d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4q-4FTqooMrEOiG6ZwbHsRO2pYPOpfe0',
    appId: '1:122960398385:ios:10a041edfd71d3ab226d10',
    messagingSenderId: '122960398385',
    projectId: 'nutriplan-e06d0',
    storageBucket: 'nutriplan-e06d0.firebasestorage.app',
    iosBundleId: 'com.example.nutriPlan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4q-4FTqooMrEOiG6ZwbHsRO2pYPOpfe0',
    appId: '1:122960398385:ios:10a041edfd71d3ab226d10',
    messagingSenderId: '122960398385',
    projectId: 'nutriplan-e06d0',
    storageBucket: 'nutriplan-e06d0.firebasestorage.app',
    iosBundleId: 'com.example.nutriPlan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdZPn5AwfYKVdF7mX_cCby41gXqKFvOMc',
    appId: '1:122960398385:web:b893698e300d545f226d10',
    messagingSenderId: '122960398385',
    projectId: 'nutriplan-e06d0',
    authDomain: 'nutriplan-e06d0.firebaseapp.com',
    storageBucket: 'nutriplan-e06d0.firebasestorage.app',
    measurementId: 'G-Y97YM63WDJ',
  );
}
